### ISSUE TITLE
Testnet version not accurately titled in pcli

### ISSUE THREAD

**Issue by pygmygoats** [penumbra-zone/penumbra#574] opened 2022-04-07 23:56 UTC
**Describe the bug**
running pcli - the interface is titled with the 004 testnet rather than the current 006 testnet

**To Reproduce**
1. git clone https://github.com/penumbra-zone/penumbra
2. cd penumbra && git checkout 006-orthosie
3. cargo build --release --bin pcli

"pcli 004-thelxinoe-361-g924f42f
The Penumbra command-line interface."

**Expected behavior**
Would expected the interface to be titled "pcli 006-orthosie"

**Screenshots**
<img width="612" alt="Screen Shot 2022-04-07 at 6 53 51 PM" src="https://user-images.githubusercontent.com/103226075/162337542-82613aa4-a3a6-4c3d-bcbe-b83b582a7616.png">

**Comment by hdevalence** [comment] 2022-04-08 07:46
Thanks! My first guess about what's happening here is that the version is auto-derived from the git information, and somehow (maybe a missing tag?) there's not the correct information for it to pick up the correct details.

**Comment by hdevalence** [comment] 2022-04-11 04:58
Added to Herse milestone; we should figure out how to correctly do a git tag for Herse so that `vergen` will pick up the version.

**Comment by hdevalence** [comment] 2022-04-11 16:22
What's mysterious is that it's showing up for `004-thelxinoe`, but we *do* have git tags for the other versions:

<img width="356" alt="Screen Shot 2022-04-11 at 9 20 46 AM" src="https://user-images.githubusercontent.com/44879/162785762-8145b520-c0fa-43ef-939f-ed99525d001b.png">


Perhaps we need to have the tag name be the first line of the tag, or something?

**Comment by hdevalence** [comment] 2022-04-11 22:01
It looks like the problem is that the `vergen` crate only parses "normal" git tags (created with `git tag -a`), and not "lightweight" git tags.  This will be fixed for Herse and going forward.

**Closed by hdevalence** 2022-04-11 22:01 UTC
