### ISSUE TITLE
CORS settings on testnet GRPC endpoint are broken again

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4318] opened 2024-05-04 18:48 UTC
**Describe the bug**

https://buf.build/studio/penumbra-zone/penumbra/penumbra.core.app.v1.QueryService/AppParameters?target=https%3A%2F%2Fgrpc.testnet.penumbra.zone&selectedProtocol=grpc-web&share=s2KqrgUA

Does not work in FF with a CORS error.

**Comment by conorsch** [comment] 2024-05-06 15:11
Tested this shortly after you reported it, and was able to reproduce, although I didn't bother to screenshot it. Intriguingly, the problem was also evident on the solo node `https://solo-pd.testnet.plinfra.net` ([buf studio link](https://buf.build/studio/penumbra-zone/penumbra/penumbra.core.app.v1.QueryService/AppParameters?target=https%3A%2F%2Fsolo-pd.testnet.plinfra.net&selectedProtocol=grpc-web)), so it definitely wasn't any reverse-proxies that we run causing the problem. We added an integration test in https://github.com/penumbra-zone/penumbra/pull/3870 to guard against regressions, and that hasn't failed, and polling the endpoints directly shows that they're still serving correctly:

<details>
<summary>
curl results on endpoint calls
</summary>

```
❯ curl -I https://grpc.testnet.penumbra.zone
HTTP/2 200
access-control-allow-origin: *
access-control-expose-headers: *
content-type: text/html
date: Mon, 06 May 2024 15:05:08 GMT
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
content-length: 481

❯ curl -I https://solo-pd.testnet.plinfra.net
HTTP/2 200
content-type: text/html
content-length: 481
access-control-allow-origin: *
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
access-control-expose-headers: *
date: Mon, 06 May 2024 15:05:19 GMT
```
</details>

Testing this morning, however, showed it's working just fine:

![buf-studio-working-again](https://github.com/penumbra-zone/penumbra/assets/657862/0834b3a9-2d5a-4c64-b8ce-75f23ca51593)


No changes were made to any of our deployments. Therefore I believe this a transitory change on Buf's end, although I can't find a citation for that. I also made sure to test in Chrome, and Buf Studio is working well with both our endpoints linked above. I'm closing this issue for now, but please re-open if you are still having problems!

**Closed by conorsch** 2024-05-06 15:11 UTC
Labels: _P-V1, _P-high, needs-refinement
