### ISSUE TITLE
Implement AssetMetadataByIds endpoint of ShieldedPool service

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#4688] opened 2024-07-02 00:28 UTC
https://github.com/penumbra-zone/penumbra/blob/64f3399aa9eb6df8d02ed6c91628945976cbf046/crates/core/component/shielded-pool/src/component/rpc.rs#L67-L72

any client using the web block processor will be ratelimited immediately when attempting genesis block sync. this is due to the massive number of requests issued during initial validator discovery (currently, there are 437 validators).

PR exists at https://github.com/penumbra-zone/web/pull/1392 in web to avoid the behavior, but most of these requests could become a single request if this batch request endpoint were implemented.

**Comment by Valentine1898** [comment] 2024-07-11 22:26
This is a duplicate of https://github.com/penumbra-zone/penumbra/issues/4162 that was closed in favor of https://github.com/penumbra-zone/web/issues/1189

**Closed** 2024-08-15 05:10 UTC
Labels: needs-refinement
