### ISSUE TITLE
view: test syncing against an upgraded node

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3485] opened 2023-12-06 20:46 UTC
Similar to #3484, but synchronizing against a regular upgraded node.

**Comment by conorsch** [comment] 2023-12-07 01:39
I tried this today, and failed. Ostensibly the upgrade process worked OK on the fullnode, but trying to sync fails:

```
❯ pcli --home ~/.local/share/pcli-devnet view balance
Scanning blocks from last sync height 178 to latest height 0
[0s] ██████████████████████████████████████████████████ 18446744073709551438/18446744073709551438 0/s ETA: 0s
Error: status: Internal, message: "Worker failed: Wrong block height 1 for latest sync height 178", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

```

The nodes do at least respond to queries, but they show a reset on height:

```
❯ pcli --home ~/.local/share/pcli-devnet q chain info -v
Chain Parameters:
                                                                        
 Chain ID                                penumbra-testnet-rhea-fffba681 
 Epoch Duration                          50                             
 Unbonding Epochs                        2                              
 Active Validator Limit                  80                             
 Base Reward Rate (bps^2)                30000                          
 Slashing Penalty (Misbehavior) (bps^2)  10000000                       
 Slashing Penalty (Downtime) (bps^2)     10000                          
 Signed Blocks Window (blocks)           10000                          
 Missed Blocks Max                       9500                           
 Proposal Deposit Amount (upenumbra)     10000000                       
 IBC Enabled                             true                           
 Inbound ICS-20 Enabled                  true                           
 Outbound ICS-20 Enabled                 true                           
Chain Info:
                          
 Current Block Height   0 
 Current Epoch          0 
 Total Validators       2 
 Active Validators      2 
 Inactive Validators    0 
 Jailed Validators      0 
 Tombstoned Validators  0 
 Disabled Validators    0 
```

It's very possible I screwed up somewhere in the upgrade docs: https://github.com/penumbra-zone/penumbra/wiki/Performing-upgrades I've left the devnet running, so we can inspect state and see if we can spot the problem. @erwanor perhaps we can pair on this.

**Comment by erwanor** [comment] 2023-12-07 03:45
I was unable to reproduce on a local devnet when doing a *fresh* sync for a client that had some transactions pre-upgrade. My suspicion is that sync might be broken if you don't reset the client. If that's the case we should fix this, we can dig into this tomorrow. On the flip side I was able to test that sync'ing from scratch and viewing specific transactions works.

**Comment by hdevalence** [comment] 2023-12-07 08:19
I'm wondering if this is because part of the sync logic is getting block height data from the tendermint proxy, rather than from the app state, or something like that?

**Comment by erwanor** [comment] 2023-12-07 13:49
I tested two more things, I think we should still have independent testing but here is what I found:

- Tested that view sync doesn't require any reset: I made some transactions, including one with a memo, performed an upgrade, and I was able to `pcli sync` and query the individual transactions.
- Tested that trying to view synchronize on a partially upgraded node (e.g. pd is online, but comet is down) doesn't lead to an inconsistent state, and instead errors.

**Comment by erwanor** [comment] 2023-12-07 13:52
@hdevalence It does, but that shouldn't matter because we specify a non-zero height so there shouldn't ever be a reported block 1, other than the bona fide block 1 that occurred pre-upgrade.

@conorsch After doing some testing, I'm leaning towards a possible configuration error. Is it possible that the config `pcli-devnet` points to the wrong devnet? I'll also review the wiki for upgrades.

**Comment by conorsch** [comment] 2023-12-07 18:00
We paired on this today and discovered a few things that surfaced only due to our testing in a multi-validator setup. We must make three (3) changes:

1. The `priv_validator_state.json` file should _not_ be preserved. Rather, it should be reset to initial state as defined in https://github.com/penumbra-zone/penumbra/blob/bf131150f1e1b22174ca2afd0631fd108509c18e/crates/bin/pd/src/testnet/generate.rs#L506-L517 The `pd upgrade` command should emit this JSON file as an artifact, same as it does genesis.json.
2. Next, we should update the docs to include mention of handling that `priv_validator_state.json` file.
3. Finally, the genesis time currently defaults to utc.now, which breaks consensus across multiple validators. We should update the `pd upgrade` logic to emit a static timestamp, so that genesis files are identical. Optionally, `pd upgrade` could take a flag to override this.

Example of genesis time differing between two validators:

```diff
❯ diffoscope val-*
 |#                                                                                                                                                                                                                                              |  N/A%  None  ETA:  --:--:-- --- val-0-genesis.json
+++ val-1-genesis.json
├── Pretty-printed
│ @@ -18,11 +18,11 @@
│          },
│          "validator": {
│              "pub_key_types": [
│                  "ed25519"
│              ]
│          }
│      },
│ -    "genesis_time": "2023-12-07T00:58:02.209678751Z",
│ +    "genesis_time": "2023-12-07T01:05:20.847960753Z",
│      "initial_height": "185",
│      "validators": []
│  }
```

**Comment by conorsch** [comment] 2023-12-07 21:59
See https://github.com/penumbra-zone/penumbra/pull/3491 for the changes requested above. Wiki has also been updated accordingly.

**Comment by hdevalence** [comment] 2023-12-08 19:28
Can you try:

- creating a new pcli home directory 
- importing keys into it
- running a sync with --features "sct-divergence-check" to pinpoint the moment of sct divergence?

**Comment by hdevalence** [comment] 2023-12-08 19:30
It's possible there's something trivial happening with the SCT operations at the upgrade boundary, and if we can confirm that we can zoom in on the cause. This is really exciting!

**Comment by conorsch** [comment] 2023-12-08 19:34
@hdevalence 

```
❯ RUST_LOG=penumbra=debug pcli --home ~/.local/share/pcli-devnet-2 view sync
2023-12-08T19:34:17.339311Z  INFO penumbra_view::worker: starting client sync
2023-12-08T19:34:17.500261Z DEBUG latest_known_block_height: penumbra_view::service: latest_block_height=13555 node_catching_up=false latest_known_block_height=13555
Scanning blocks from last sync height 1 to latest height 13555
[0s] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░       0/13554   0/s ETA: 0s
2023-12-08T19:34:17.596855Z ERROR penumbra_view::worker: e=SCT divergence detected at height 1: expected 28c5d4e868cf25b29cd0380abb67d3aafdfc056672ae6e6a56f395b704b3ed0f, got 3509529e8fedf5df119f7be3ea236ebcfe15e3c053fa50c0f9d0c4f2dcdb3b01
2023-12-08T19:34:17.596956Z  INFO penumbra_view::worker: view worker error e=SCT divergence detected at height 1: expected 28c5d4e868cf25b29cd0380abb67d3aafdf
[0s] ██████████████████████████████████████████████████   13554/13554   140213/s ETA: 0s
```

**Comment by conorsch** [comment] 2023-12-08 19:58
fn logs show a panic, that doesn't cause pd to crash:

```
5039 2023-12-08T19:56:34.205310Z  INFO abci:BeginBlock{height=13817}: pd::consensus: beginning block time=Time(2023-12-08 19:56:28.818124306)
5040 2023-12-08T19:56:34.210926Z  INFO abci:EndBlock{height=13817}:event{kind="sct_anchor"}: pd::consensus: k="height" v="13817"
5041 2023-12-08T19:56:34.211019Z  INFO abci:EndBlock{height=13817}:event{kind="sct_anchor"}: pd::consensus: k="anchor" v="1e425ef985a1dbca66e7264f978db254cec0bf8246dc804c6b175cd9e5bf3501"
5042 2023-12-08T19:56:34.211149Z  INFO abci:EndBlock{height=13817}:event{kind="sct_block_anchor"}: pd::consensus: k="height" v="13817"
5043 2023-12-08T19:56:34.211227Z  INFO abci:EndBlock{height=13817}:event{kind="sct_block_anchor"}: pd::consensus: k="anchor" v="0100000000000000000000000000000000000000000000000000000000000000"
5044 2023-12-08T19:56:34.268743Z  INFO abci:Commit: pd::consensus: committed block app_hash=RootHash("42f67e7e3b4998ceb01f4fd1c97f939843931c41eb34791f10012d6b15a3a7dd")
5045 thread 'tokio-runtime-worker' panicked at crates/core/component/compact-block/src/component/rpc.rs:153:26:
5046 compact block for in-range height must be present

```

**Comment by conorsch** [comment] 2023-12-09 00:54
Trying again with the changes in #3500, I'm able to view txs post-upgrade—mostly. See terminal session here: https://gist.github.com/conorsch/fa1b5fe28741e78f51929eeb69315a91 All historical `send` txs are visible immediately, but governance actions such as "initial delegation" and "vote yes" were not found, oddly. For reference, here's the mapping of tx ids I recorded prior to upgrade:

```
❯ cat src/notes/upgrade-testing/pre-upgrade-txs.txt 
# initial delegation:
d6949ac23f31a6a775d1d7d0f3446e8e49ce98faf87ba3e60813f83de51e6b85
# send tx:
edbebd9fc238888fce3db3ffa483b8a0add8d08d8127ca2373d6c66a57eecd91 @ height 85
b370b66d52d4fad80dbfbba83a7e3f8fa2a36af43305dcfe976ec5a66b68d291 @ height 98
# submit proposal:
4eff02ca51a247d9b47425279d485ea493168122a739a7cb8dcfecdd1cda7f00 @ height 118
# vote yes:
aa86ca9d822f940a0e2b1ce564696c50232f9614b875a1f5f51ce242fd2b3a9c
# another send tx:
e1fb997d4ddb339c3ec1ee1720160c96690b9dc8a2f14edbd7227cc92cf6a0ba @ height 146
# halt at 250
```

However, after reimporting my keys in a fresh pcli dir and `sync`ing from scratch, txs do appear! So this isn't the end of the world, but shows that we have some view service kinks to work out. (IMO these aren't blocking.)

**Comment by conorsch** [comment] 2023-12-09 01:03
Darn, apparently new gov proposals nuke old ones:

```
# prior to upgrade
❯ pcli --home ~/.local/share/pcli-devnet q governance proposal 0 definition
title = "The first upgrade proposal on the devnet"
description = "Let's give it a go"

[upgradePlan]
height = "250"

# post-upgrade, we resubmitted a new gov proposal, and then tried:
❯ pcli --home ~/.local/share/pcli-devnet q governance proposal 0 definition
title = "Bellevue chain upgrade test (devnet)"
description = "This upgrade should not break light clients!!"

[upgradePlan]
height = "1000"
```

That shouldn't happen!

**Comment by hdevalence** [comment] 2023-12-09 01:25
> All historical send txs are visible immediately, but governance actions such as "initial delegation" and "vote yes" were not found, oddly.

I can think of one reason: the distinction here could be between transactions that are cached in the view service and transactions that aren't. For the send transactions, they're flagged during scanning, and the view server will download them and index them locally. Then, when you view the transaction, the tx is found locally and returned.  But if the transaction isn't flagged during scanning and indexed locally, the query wouldn't find it in the local view service, and then it would fall back to querying the fullnode, which would proxy through to comet, which wouldn't have the old transactions...

If this theory is correct, then I think this is probably not a significant problem to put resources into solving. If we have nonzero gas prices, every transaction will have a spend, and then it would be detected.

**Comment by conorsch** [comment] 2024-01-04 21:42
> It's possible there's something trivial happening with the SCT operations at the upgrade boundary,  

That problem, and the problem of gov counters being wrong post-upgrade, were resolved by https://github.com/penumbra-zone/penumbra/pull/3500. We do still have the problem of

> All historical send txs are visible immediately, but governance actions such as "initial delegation" and "vote yes" were not found, oddly.

but as @hdevalence says, we don't need to solve that now. Closing as resolved, given all the testing above.

**Closed by conorsch** 2024-01-04 21:42 UTC
Labels: P-next release
