### ISSUE TITLE
dex: unable to swap entirety of a specific asset

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#2939] opened 2023-08-16 16:18 UTC
**Describe the bug**
When performing swaps in the DEX, the action will fail if the entire balance of a specific asset is consumed. To workaround this problem, you can try to structure the swap to consume 99% (anything less than 100%) of the amount available. 

**To Reproduce**
I'm sorry to say I don't have specific STR documented. I'm filing this issue after discussion with Zpoken that they've been bitten by the same. 

**Expected behavior**
Swaps can consume the entirety of a held asset.

**Additional context**
Zpoken reported this in sync today, and yesterday I filed a similar issue in the context of IBC withdrawals: https://github.com/penumbra-zone/penumbra/issues/2936

**Comment by erwanor** [comment] 2023-08-16 16:30
>When performing swaps in the DEX, the action will fail if the entire balance of a specific asset is consumed.

Just to make sure I understand correctly, the action will fail to submit i.e. one of the pre-submission checks will fail client side?

**Comment by zbuc** [comment] 2023-08-16 20:08
I'm having trouble reproducing:

```shell
$ cargo run --bin pcli --release -- --node http://localhost:8080 tx position order sell 100test_usd@0.001penumbra

building transaction...
finished proving in 0.700 seconds [4 actions, 3 proofs, 2563 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: 92989fb9ff6b62ce3289f41c90bb808474262fd52b9d6319a95da8a5d32cf005 @ height 20
```

```shell
$ cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 0.1penumbra --into test_usd

building transaction...
finished proving in 0.863 seconds [3 actions, 3 proofs, 2367 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: 0004f3d023528647bd85518b67cc5bebfb0d7dad31ef32f544a72032a37ae045 @ height 30
Swap submitted and batch confirmed!
You will receive outputs of 100test_usd and 0penumbra. Claiming now...
building transaction...
finished proving in 0.533 seconds [1 actions, 1 proofs, 571 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: b10033c2174696585ce7d1e8b331bda0fea8e39907c8840e1f51642d5fae013f
```

```shell
$ cargo run --bin pcli --release -- -n http://localhost:8080 query dex positions test_usd:penumbra

 ID                                                                State    Fee    Sell Price      Reserves
 plpid1z3t9e4w5d9da2a2cy44w6axdljxqrf8xpx33elujwun92jpxanrs527fl2  opened  0bps  1000test_usd  100mpenumbra
 ```
 
 ```shell
$ cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 100test_usd --into penumbra

building transaction...
finished proving in 0.822 seconds [3 actions, 3 proofs, 2375 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: da806ac9a292c31a0b2e0ae4ad1e9f98598a9944bc60ab799f49989f11798577 @ height 57
Swap submitted and batch confirmed!
You will receive outputs of 0test_usd and 99.999mpenumbra. Claiming now...
building transaction...
finished proving in 0.542 seconds [1 actions, 1 proofs, 571 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: 6a47b5817623d6267299998ef8427978cd29899636a426e36e47185e639e3bff
```

```shell
$ cargo run --bin pcli --release -- -n http://localhost:8080 query dex positions test_usd:penumbra

 ID                                                                State    Fee    Sell Price     Reserves
 plpid1z3t9e4w5d9da2a2cy44w6axdljxqrf8xpx33elujwun92jpxanrs527fl2  opened  0bps    1mpenumbra  100test_usd
 └──────────────────────────────────────────────────────────────▶          0bps  1000test_usd   1upenumbra
 ```
 
 Did notice something weird though... the position disappears from the positions query output:
 
 ```shell
 $ cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 1test_usd --into penumbra
 
 building transaction...
finished proving in 0.796 seconds [3 actions, 3 proofs, 2373 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: be7a9e840707d98d90cd6953ac4f5defd63946ed3f7d2abe682180eace2ce56f @ height 99
Swap submitted and batch confirmed!
You will receive outputs of 999000000000000000wtest_usd and 1upenumbra. Claiming now...
building transaction...
finished proving in 0.559 seconds [1 actions, 1 proofs, 577 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: e6e316bc6a7e112ed0bd53d5d4ab3d35e9d690908e8004ed99b0181440c6c3cd
```

```shell
$ cargo run --bin pcli --release -- -n http://localhost:8080 query dex positions test_usd:penumbra

 ID  State  Fee  Sell Price  Reserves
 ```

**Comment by erwanor** [comment] 2023-09-15 16:46
Closing this for now since we haven't been able to reproduce. We can re-open it if it occurs again of course.

**Closed by erwanor** 2023-09-15 16:46 UTC
