### ISSUE TITLE
Spurious error related to "note commitment missing"

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4601] opened 2024-06-12 19:04 UTC
See: https://discord.com/channels/824484045370818580/981304070444814367/1248691717322838118

The basic failure mode involves doing transactions in pcli, such as contributing to the ceremony, and failing to send a transaction because of the error `Note commitment missing`. This seems spurious, in that it doesn't reproduce easily.

We should look into this more, as we've seen several reports about this.

Also, it seems like Galileo was having these errors back in November as well.

**Comment by cratelyn** [comment] 2024-06-12 19:14
this looks like the same error observed in https://github.com/penumbra-zone/penumbra/issues/4574#issuecomment-2155251849

**Comment by zbuc** [comment] 2024-06-17 17:21
This is reproducibly happening for me on the current testnet

**Comment by cratelyn** [comment] 2024-06-24 16:26
there are a collection of errors, all filed around the same time, that relate
to inconsistent behavior when viewing transactions. i took some time to gather
these, and write up my understanding of the current state of affairs:

#4452 reports that the view service's response streams terminate when an error
is encountered. #4465 reports that the view service misses some tx's when
scanning. #4577 describes the view service being corrupted with invalid
anchors.

#4584, #4574, and #4238 all describe issues with `pcli` failing to collect
various information. #4584 reports that pcli fails to
`query dex all-positions`, #4574 reports that pcli fails to `sweep`, and #4238
reports that pcli fails to detect delegator votes.

#4601 describes `"note commitment missing"` errors when making transactions
with pcli, which is the underlying issue behind #4574 in particular.

in response to this, we have already shipped a few changes to address this:
- #4453 avoids recording invalid `Metadata`.
- #4578 adds height checks to the view service.
- #4586 adds height checks to the compact-block server.

these have all shipped in v0.77.3. 

#4605 added test coverage for `pcli sweep`, and #4617 made additional changes
to facilitate exercising pcli in mock consensus tests. #4517 tracks an issue
that soft blocks us from adding more test coverage of the view service, which
caused us to disable that test coverage in #4633.

**at this point i believe that #4601 and #4574 can also be closed via #4578
and #4586.** these added defensive checks to the compact-block RPC and the
view service to help keep syncing deterministic and reliable, which is a
common thread between all of these issues. going forward, we can build out
more assurance of this system by addressing #4517 next.

**Closed** 2024-06-26 15:01 UTC
Labels: C-bug, needs-refinement
