### ISSUE TITLE
clients: ensure penumbra clients work across upgrade boundaries

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3357] opened 2023-11-15 21:38 UTC
Penumbra’s client logic _requires_ access to full block data, proxied through to Tendermint/CometBFT. Does this get preserved across upgrade boundaries?

_Why this feature is required pre-mainnet_

We can’t lose history needed for clients to retain their state. Compact blocks aren’t sufficient.

_What we need to implement_

- [ ] have `pd` store a copy of all of the block data
- [ ] ???

**Comment by hdevalence** [comment] 2023-12-06 00:03
Duplicate of #3451

**Closed by hdevalence** 2023-12-06 00:03 UTC
Labels: P-next release, P-V1
