### ISSUE TITLE
Tracking Issue: Fees

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3290] opened 2023-11-07 22:16 UTC
This issue captures the state of fees work.

### Complete
- [x] https://github.com/penumbra-zone/penumbra/issues/2970
- [x] https://github.com/penumbra-zone/penumbra/issues/3194

### Remaining
- [x] https://github.com/penumbra-zone/penumbra/issues/3153
- [ ] https://github.com/penumbra-zone/penumbra/issues/3164
- [ ] https://github.com/penumbra-zone/penumbra/issues/2972
- [ ] #3633

**Comment by aubrika** [comment] 2024-01-23 18:12
Closed as duplicate of #3367

**Closed by aubrika** 2024-01-23 18:12 UTC
