### ISSUE TITLE
Add recommendation to `pcli` to try `pcli tx sweep` for planning failures

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#4416] opened 2024-05-20 17:29 UTC
When attempting to plan transactions, if a wallet has too many dust notes it's likely that the user will receive an "Error: can't plan delegation"/"failed to plan transaction after 100 iterations" error message. The way to resolve this is to run `pcli tx sweep` to combine the low-value notes, however the current error message doesn't make this clear and it's been a point of confusion for users.

Since validators will mostly be using `pcli`, it seems worthwhile to add a hint to the text that they may wish to try running `pcli tx sweep` and re-submitting the transaction.

**Comment by aubrika** [comment] 2024-05-22 19:06
Closed as duplicate of #4414

**Closed by aubrika** 2024-05-22 19:06 UTC
Labels: _P-V1, _P-medium
