### ISSUE TITLE
`pcli` position replication should support ranged liquidity

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4396] opened 2024-05-15 22:42 UTC
**Is your feature request related to a problem? Please describe.**

Currently `pcli tx lp replicate` supports full-range xyk liquidity. However, this is not very capital-efficient.

**Describe the solution you'd like**

It would be good to support liquidity in a range, like UniV3. Maybe we call it `univ3` and have the same parameters as UniV3 liquidity?

**Comment by aubrika** [comment] 2024-05-22 17:14
Closed as duplicate of #4112

**Closed by aubrika** 2024-05-22 17:14 UTC
Labels: _P-high, needs-refinement
