### ISSUE TITLE
Governance support for IBC actions

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3364] opened 2023-11-15 21:56 UTC
_Why this feature is required pre- mainnet_

Subjecting IBC to governance is necessary for the IBC implementation on Penumbra to be suitable for handling real-world funds. N.B. this feature overlaps with the Governance and Upgrades planning projects.

_What we need to implement_

- [x] https://github.com/penumbra-zone/penumbra/issues/2173

**Comment by erwanor** [comment] 2024-01-08 22:45
Duplicate of #2173

**Closed by erwanor** 2024-01-08 22:45 UTC
Labels: P-V1
