### ISSUE TITLE
Configure the existing `Swap` actions to use the new liquidity positions rather than the `StubCpmm` (should there be a higher level encapsulation here over the liquidity positions, similar to `StubCpmm`? probably)

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1907] opened 2023-01-27 23:53 UTC

**Comment by conorsch** [comment] 2023-02-10 18:46
This wasn't worked on in 44; it's pretty far out. Moving to future, and will continue to track in #1725.

**Comment by hdevalence** [comment] 2023-03-15 21:35
Close as duplicate of #1906

**Closed by hdevalence** 2023-03-15 21:35 UTC
Labels: E-multi-day
