### ISSUE TITLE
`pcli tx withdraw` uses the wrong chain's timeout height

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3041] opened 2023-09-15 20:08 UTC
**Describe the bug**

`pcli tx withdraw` uses the local chain to determine the timeout height, but the parameter actually controls the counterparty chain:

```
~/c/p/penumbra2 (allow-no-prehash-key|✚2) $ cargo run --release --bin pcli -- -n http://localhost:8080 tx withdraw --to osmo1kh0fwkdy05yp579d8vczgharkcexfw582zj488 --channel 0 100penumbra
    Finished release [optimized] target(s) in 0.36s
     Running `target/release/pcli -n 'http://localhost:8080' tx withdraw --to osmo1kh0fwkdy05yp579d8vczgharkcexfw582zj488 --channel 0 100penumbra`
Scanning blocks from last sync height 377 to latest height 377
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
building transaction...
finished proving in 1.355 seconds [3 actions, 2 proofs, 1910 bytes]
broadcasting transaction and awaiting confirmation...
Error: status: Internal, message: "could not broadcast transaction: Error submitting transaction: code 1, log: timeout height 0-29177 is less than the latest height 2688215", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

The timeout timestamp works fine because the chains probably have roughly synced clocks.

Maybe we can query the Penumbra-chain's client info, or maybe we can use a timestamp instead?

**Comment by hdevalence** [comment] 2023-09-15 20:10
Setting a larger timeout height also fails:
```
Error: status: Internal, message: "could not broadcast transaction: Error submitting transaction: code 1, log: timeout height 0-2690215 is less than the latest height 2688215", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

**Comment by hdevalence** [comment] 2023-09-15 20:36
The above issue was caused by using a bare integer rather than an IBC height, so we ignored the revision number (in that case it was `5-2688215`)

**Comment by conorsch** [comment] 2023-11-28 21:21
We're not sure if this is still an issue, as the `pcli` interface has changed a bit. Even if the issue is still in place, it's not critical to fix by Testnet 64 Titan (#3408), since it's client-side code, so we can always point-release (i.e. non-consensus-breaking) to address it.

**Comment by hdevalence** [comment] 2024-03-22 05:09
@avahowell is this still a problem?

**Comment by avahowell** [comment] 2024-03-22 06:24
This was resolved in 

https://github.com/penumbra-zone/penumbra/pull/3558

pcli uses the client metadata to look up a default timeout (on the counterparty).

**Closed by avahowell** 2024-03-22 06:24 UTC
Labels: A-IBC, _P-V1, _P-medium
