### ISSUE TITLE
stake(bug): unstaking from a validator not working. 

### ISSUE THREAD

**Issue by cryptomaharlika** [penumbra-zone/penumbra#3612] opened 2024-01-15 12:05 UTC
**Describe the bug**
running the code below in pcli resulting a "status: OutOfRange" error

"pcli tx undelegate 266.3delegation_penumbravalid1kn4ymvhmmnsuru6utypakqsrm5mvafsxuqu640zfq5uptfktmy9s4v8xjd"

**Screenshots**

![EROR](https://github.com/penumbra-zone/penumbra/assets/154934527/987761ee-6a1d-4aed-a4ab-e04704645073)

**Comment by erwanor** [comment] 2024-01-15 17:06
Thanks for the report, I'm going to look into this!

**Comment by erwanor** [comment] 2024-01-17 19:40
@cryptomaharlika I'm not able to reproduce, I was able to delegate/undelegate/claim from validator `1000delegation_penumbravalid1kn4ymvhmmnsuru6utypakqsrm5mvafsxuqu640zfq5uptfktmy9s4v8xjd`. 

Could you let me know the following:

1. Run `pcli debug info` and paste the result here
2. Run `NO_COLOR=1 RUST_LOG=debug  pcli tx undelegate 266.3delegation_penumbravalid1kn4ymvhmmnsuru6utypakqsrm5mvafsxuqu640zfq5uptfktmy9s4v8xjd &> log_bug.txt` and drop the file to me in DMs on Discord (ping me @erwanor)

**Comment by cryptomaharlika** [comment] 2024-01-18 05:42
@erwanor  I have moved from old desktop (Ubuntu) to laptop (Debian). I am currently stuck at 70%. 
Once fully sync I will do that and check if all seems to work on my side. 

Will Dm you at discord for this. 

Much appreciated your help on this.

**Comment by cryptomaharlika** [comment] 2024-01-21 07:35
Hi! I already found out why my sync is very slow. 

now i am fully since. 

trying to undegate but still have an error. 

See below :

Error: status: OutOfRange, message: "Error, message length too large: found 5615319 bytes, the limit is: 4194304 bytes", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

**Comment by cryptomaharlika** [comment] 2024-01-21 07:35
![Uploading 000.png…]()

**Comment by hdevalence** [comment] 2024-02-09 00:32
Our suspicion is that this would have been fixed by `pcli tx sweep`; since the testnet is gone we won't be able to repro.

**Closed by hdevalence** 2024-02-09 00:32 UTC

**Comment by cryptomaharlika** [comment] 2024-02-13 03:00
Hi. All is working perfectly now with testnet v0.67.0

Thank you guys!
